import { Poppins } from "next/font/google";
import "./globals.css";

// Define the font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // you can add more weights if needed
  display:"swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
